### ISSUE TITLE
一个是map,一个通过list填充,list不为空时,导致下面的map填充数据都为空了

### ISSUE THREAD

**Issue by L429** [lkzgit/springboot-easyExcle#1]
您好,之前看到您提问的那个问题:表格数据组合填充,一个是map,一个通过list填充,list不为空时,导致下面的map填充数据都为空了 请问解决了没

**Comment by lkzgit** [comment]
没有 我把他全部换成对象了

**Comment by L429** [comment]
一个对象包含list和map的数据吗 还是分别封装

**Comment by L429** [comment]
> 没有 我把他全部换成对象了

大佬 麻烦有空说详细一些吧 万分感谢

**Comment by L429** [comment]
欧克欧克 大佬 我找到问题了 和我项目中的poi依赖冲突了
